### PR TITLE
colab: fixing typos

### PR DESCRIPTION
**Pull request by matildepark**
Running this script. Thank you for handling my exact use case. :)

Just fixing things as I try to run it.

### CODE REVIEW

**Comment by s-crypt** [comment]
Thanks for the fixes! I really didn't think anyone would actually see this, let-alone use it haha

**Comment by matildepark** [comment]
It wasn't feasible for me on colab anyway bc 63000 listens at 1 lookup per second. timed out after a few hours. I cobbled a way together thanks to this notebook though :)

**Comment by s-crypt** [comment]
Yeah that time limit should be lowered. The API limits are like 50/second, I think I just forgot to change it from my testing times. I think I increased it from 1/s to 10/s in c6782e87582e37f6d5b433471bbd57ebe27cf0a9

**Comment by matildepark** [comment]
I think the API limit is 1/second in the Musicbrainz API though, see https://musicbrainz.org/doc/MusicBrainz_API/Rate_Limiting:

> The rate at which your IP address is making requests is measured. If that rate is too high, all your requests will be declined (http 503) until the rate drops again. Currently that rate is (on average) 1 request per second.
> 
> For example: if your requests are coming in at 4 requests per second, we don't honour 25% of them and decline the other 75% - we decline 100% of them, until the rate drops to 1 per second or lower.

**Comment by s-crypt** [comment]
I see. I was reading the user-agents section thinking that had presciendence, but it looks like it does not.
> For "python-musicbrainz/0.7.3": we allow through (on average) 50 requests per second, and decline the rest (though recently this has not been hit).

Since the notebook uses the python library I thought it would allow 50/s but since it is from a static IP I guess not? The wording is a bit vague to me.
Is it talking about 50/s _globally_ per _application_? (rhetorical, since it doesn't matter now)

**Pull request merged**
